import React from "react";

export default function Description(){
    return(
        <section>
            <section>
                <section>
                    <div>
                        <img
        src=""
      />
                    </div>
                </section>
                <section>
                    <div>
                    <img
        src=""
      />
                    </div>
                    <div><img
        src=""
      />
                    </div>
                    <div>
                    <img
        src=""
      />
                    </div>
                </section>
            </section>
            <section>
                <section>
                    <h2></h2>
                    <div>
                        <p>
                            <h4>Descripción:</h4>
                        </p>
                        <p>
                            <h4>Precio:</h4>
                        </p>
                    </div>
                </section>
                <section>
                    <button>Contactar</button>
                    <button>Añadir</button>
                </section>
            </section>
        </section>
    )
}